### ISSUE TITLE
Warning 14217

### ISSUE THREAD

**Issue by mcpacific** [TwilioDevEd/task-router-laravel#5]
I noticed if you don't answer the call it eventually goes to voicemail as it should.  However, Twilio gives a 14217 warning:

Dial->Queue: Could not find or accept provided reservationSid

**Comment by well1791** [comment]
Hey @mcpacific could you please try #7 there are a few fixes using the latest Twilio-sdk version.

Btw I wasn't able to reproduce the same error.

**Comment by mcpacific** [comment]
I've been working away on a project but I can't wait to look at the updated code, thank you!

**Comment by mcpacific** [comment]
When cloning the Git repository phpit still installs Laravel 5.2 and original dependencies; updating to 5.5 requires performing the manual updates you've made to EventServiceProvider, etc. Perhaps updating the Git repository would be prudent?
